//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritingCenterForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WritingCenterForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_Image {
            get {
                object obj = ResourceManager.GetObject("Background Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgImage {
            get {
                object obj = ResourceManager.GetObject("bgImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Coe_College {
            get {
                object obj = ResourceManager.GetObject("Coe_College", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CWC_logo_Black_Primary {
            get {
                object obj = ResourceManager.GetObject("CWC logo_Black_Primary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CWC_logo_Black_Secondary {
            get {
                object obj = ResourceManager.GetObject("CWC logo_Black_Secondary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CWC_logo_Red_Logomark {
            get {
                object obj = ResourceManager.GetObject("CWC logo_Red_Logomark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin,password,Admin_Person,2023,NULL,0,true
        ///admin2,password,Admin_Two,2023,NULL,0,true
        ///user0,password,FirstName_LastName,2023,CS-math,8,false
        ///user1,password1,Guy_Person,2024,BIO,10,false
        ///user2,geeksquad,Person_Guy,2025,CHEM-phys,6,false.
        /// </summary>
        internal static string dummy_accounts {
            get {
                return ResourceManager.GetString("dummy_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time,Workers,Number Of Workers
        ///,,
        ///sunday11:00am-&gt;12:00pm,&quot;[&apos;Mackenzie Jones&apos;, &apos;Andrea Glandt&apos;]&quot;,2
        ///,,
        ///sunday12:00pm-&gt;1:00pm,&quot;[&apos;Mackenzie Jones&apos;, &apos;HJ Hass&apos;, &apos;Andrea Glandt&apos;, &apos;Valerie Plesha&apos;]&quot;,4
        ///,,
        ///sunday1:00pm-&gt;2:00pm,&quot;[&apos;Mackenzie Jones&apos;, &apos;HJ Hass&apos;, &apos;Andrea Glandt&apos;, &apos;Angelina Guevara&apos;]&quot;,4
        ///,,
        ///sunday2:00pm-&gt;3:00pm,&quot;[&apos;HJ Hass&apos;, &apos;Angelina Guevara&apos;, &apos;Valerie Plesha&apos;]&quot;,3
        ///,,
        ///sunday3:00pm-&gt;4:00pm,&quot;[&apos;Esme Valenzuela&apos;, &apos;Valerie Plesha&apos;, &apos;Micki Guyton&apos;]&quot;,3
        ///,,
        ///sunday4:00pm-&gt;5:00pm,&quot;[&apos;Brett Porter&apos;, &apos;Micki Gu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schedule_draft {
            get {
                return ResourceManager.GetString("schedule_draft", resourceCulture);
            }
        }
    }
}
